spring:
  application:
    name: AwsWithSpring

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring1
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: 5d41402abc4b2a76b9719d911017c592

springdoc:
  show-login-endpoint: true

logging:
  level:
    org.springframework.data.redis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus